### ISSUE TITLE
Refactor Documentation to use docs blocks

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/near_dbt#44]
We can make life much easier, especially for repeated columns, by using the [docs block](https://docs.getdbt.com/reference/dbt-jinja-functions/doc).  

 - Basically, write the column description in a markdown file i.e. models/descriptions/block_timestamp.md
 - Everywhere block_timestamp is in a .yml file, all you need to write is "{{ doc('block_timestamp') }}"
 - [Example](https://github.com/FlipsideCrypto/osmosis-models/blob/main/models/descriptions/block_timestamp.md)

**Comment by 0xissui** [comment]
So, would this be the proper usage

```
      - name: block_timestamp
        description: {{ doc('block_timestamp') }}
        tests:
          - not_null
 ```
